# Generated by Django 4.0.2 on 2022-03-27 14:30

import HAI.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='HAI/', validators=[HAI.validators.file_size], verbose_name=''),
        ),
    ]
